### ISSUE TITLE
Legacy Addresses

### ISSUE THREAD

**Issue by knoxcard** [paOol/Bitcoin-Cash-RPC#2]
I see Bitcoin cash has a new address format which has caused much confusion.  It would be nice to still use legacy addresses as we move forward and transition into the future.  _On my platform for example, I will show the new address first, but give the customer the option of switching to legacy before I completely disable legacy._

Online Converter: https://cashaddr.bitcoincash.org/
New Address: bitcoincash:qp2kz4pd5q0u4tvafwhlgakkcceqdktteuee97aw2q
Legacy Address: moJQKtGF3nzhc4ssfdpgs2gexL9T2utRE4

We can merge this code in, it's just one JS file, and integrate a function to allow for easy conversions.
https://github.com/Ayms/cashaddress

I will get around to this sometime tonight or tomorrow.  Posting it here first to see if anyone has any suggestions or objections (positive or negative) in regards to this.  It would be an optional function, so I don't see how this could go wrong.

**Comment by knoxcard** [comment]
Looks like the function already exists?
`translateAddress(address) {`

In that case, nevermind! lol, I will test tonight to see if I get the appropriate output.

**Comment by paOol** [comment]
Hello, the `translateAddress` was for the CoPay format.

I will need to update for the CashAddr format.

This is the regex i've been using meanwhile to check for the new format

`    const cashregex = /^((?:bitcoincash):)?(?:[023456789acdefghjklmnpqrstuvwxyz]){42}$/gi;`

**Comment by knoxcard** [comment]
I also run a full Bitcoin ABC node and translateAddress worked perfectly!  I am also accepting Litecoin and create an awesome code to handle receiving transactions no matter how many full nodes a server is running.  Maybe I put that code under the Wiki? and this post as well?

**Comment by knoxcard** [comment]
Seems like I can't add to Wiki, guess I have to be given permission?  Never used it before, not sure how I write to Wiki.

**Comment by knoxcard** [comment]
Thanks for the access to the repo!  I am going to fill up the Wiki with all sorts of useful codes so everyone can absorb the knowledge.
